// <auto-generated />
using System;
using JTMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JTMS.Migrations
{
    [DbContext(typeof(JTMSContext))]
    [Migration("20240517003409_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JTMS.Models.CompanyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfJobs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("JTMS.Models.MoldModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MoldAmount")
                        .HasColumnType("int");

                    b.Property<string>("MoldCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoldCut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoldInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoldPhoto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoldSize")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Paint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Process1Complete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Process2Complete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Process3Complete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProcessCompleteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Molds");
                });

            modelBuilder.Entity("JTMS.Models.ProjectModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("JobColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("JobDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProjectModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProjectModelId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("JTMS.Models.ProjectModel", b =>
                {
                    b.HasOne("JTMS.Models.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JTMS.Models.ProjectModel", null)
                        .WithMany("Projects")
                        .HasForeignKey("ProjectModelId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JTMS.Models.ProjectModel", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
